# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Public/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Public/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Public/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Public/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Public/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Public/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Public/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Public/anaconda3\\Library\\include']
Supported SIMD extensions in this Num

3. Create a null vector of size 10 (★☆☆)

In [4]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array (★☆☆)

In [5]:
arr = np.zeros((10, 10))

# get the memory size of the array
mem_size = arr.nbytes

print("Memory size of array: ", mem_size, " bytes")

Memory size of array:  800  bytes


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a = np.zeros(40)
n = 0
for i in range(10, 50):
    a[n] = i
    n += 1
print(a)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


In [11]:
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
print(a[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
print(np.arange(9).reshape(3, 3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
a = np.nonzero([1,2,0,0,4,0])
print(a)

(array([0, 1, 4], dtype=int64),)


11. Create a 3x3 identity matrix (★☆☆)

In [24]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
a = np.random.random((3,3,3))
print(a)

[[[0.50755507 0.0211933  0.43352176]
  [0.44631306 0.23881999 0.83024573]
  [0.74476418 0.586479   0.49286785]]

 [[0.48735588 0.2667407  0.6050111 ]
  [0.75354372 0.27058423 0.52230328]
  [0.09832853 0.71363667 0.88404059]]

 [[0.56705442 0.99448158 0.17873977]
  [0.01220009 0.45699848 0.93175194]
  [0.84602469 0.47332988 0.90255503]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
a = np.random.random((10, 10))
amin, amax = a.min(), a.max()
print(amin, amax)

0.00599789644568971 0.9909549144773288


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [32]:
a = np.random.random(30)
print(a.mean())

0.5445247938052608


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [48]:
a = np.zeros((10, 10))
a[0:, 0] = 1
a[0, 0:] = 1
a[0:, -1] = 1
a[-1, 0:] = 1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [41]:
a = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [53]:
a = np.ones((7,6))
a = np.pad(a, pad_width = 1, mode = 'constant', constant_values = 0)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [56]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [63]:
print(np.diag(1 + np.arange(4),k = -1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [65]:
a = np.zeros((8, 8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [66]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [71]:
tile = np.array([[1, 0], [0, 1]])
checkerboard = np.tile(tile, (4, 4))
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


22. Normalize a 5x5 random matrix (★☆☆)

In [75]:
matrix = np.random.rand(5, 5)
mean = np.mean(matrix)
std = np.std(matrix)

normalized_matrix = (matrix - mean) / std

print(normalized_matrix)

[[ 0.1744628  -1.36532712  0.46683042  1.14491505 -0.92973641]
 [ 1.09142316 -1.30375683  0.1810126   1.77940734  0.14526889]
 [-1.11785983 -1.23799159 -1.06177884  0.38356142  1.09987597]
 [-1.10860716  1.6959368   1.48502865 -1.22108698 -0.23271186]
 [-0.02568881  0.44768385  0.2498244   0.31563921 -1.05632513]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
dtype_rgba = np.dtype([
    ('r', np.uint8),  # red component
    ('g', np.uint8),  # green component
    ('b', np.uint8),  # blue component
    ('a', np.uint8)   # alpha component
])

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [78]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))
print(np.dot(a, b))

[[0.30885147 0.42236501]
 [1.09907952 0.89695926]
 [0.72080217 0.75668973]
 [0.57144833 0.30665929]
 [0.47857025 0.57112572]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [82]:
a = np.random.random(10)
a[4:8] = - a[4:8]
print(a)

[ 0.19600467  0.03872889  0.61586176  0.56463128 -0.10823082 -0.74163319
 -0.18348203 -0.34864109  0.48048149  0.64392643]


26. What is the output of the following script? (★☆☆)
// Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [83]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [84]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28. What are the result of the following expressions? (★☆☆)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

In [85]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Эльза\AppData\Local\Temp\ipykernel_18152\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\Эльза\AppData\Local\Temp\ipykernel_18152\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


29. How to round away from zero a float array ? (★☆☆)

In [86]:
a = np.array([-2.7, -1.5, -0.3, 0.3, 1.5, 2.7])
a_rounded = np.copysign(np.ceil(np.abs(a)), a)
print(a_rounded)

[-3. -2. -1.  1.  2.  3.]


30. How to find common values between two arrays? (★☆☆)

In [93]:
print(np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1]))

[1 3]


31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [95]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

In [96]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [101]:
today = np.datetime64('today', 'D')

yesterday = today - np.timedelta64(1, 'D')

tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday's date:", yesterday)
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)

Yesterday's date: 2023-03-25
Today's date: 2023-03-26
Tomorrow's date: 2023-03-27


34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [102]:
dates = np.arange(np.datetime64('2016-07-01'), np.datetime64('2016-08-01'), np.timedelta64(1, 'D'))

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [104]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [108]:
a = np.random.rand(5) * 10
# Extract the integer part using numpy.floor()
int_part1 = np.floor(a)
print(int_part1)
# Extract the integer part using numpy.trunc()
int_part2 = np.trunc(a)
print(int_part2)
# Extract the integer part using numpy.astype()
int_part3 = a.astype(int)
print(int_part3)
# Extract the integer part using the modulo operator
int_part4 = a % 1
print(a - int_part4)
print(a)

[5. 8. 9. 9. 9.]
[5. 8. 9. 9. 9.]
[5 8 9 9 9]
[5. 8. 9. 9. 9.]
[5.66541329 8.27417238 9.74933745 9.65224475 9.497026  ]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [110]:
a = np.zeros((5, 5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [111]:
def my_generator():
    for i in range(10):
        yield i
a = np.fromiter(my_generator(), dtype=int)

print(a)

[0 1 2 3 4 5 6 7 8 9]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [112]:
a = linspace(0, 1, 10)
print(a)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


40. Create a random vector of size 10 and sort it (★★☆)

In [113]:
a = random.random(10)
print(np.sort(a))

[0.09253613 0.155663   0.45538989 0.55178692 0.56429744 0.74043077
 0.74585773 0.8037494  0.88969109 0.99595284]


41. How to sum a small array faster than np.sum? (★★☆)

In [114]:
a = np.array([1, 2, 3, 4, 5])
print(np.add.reduce(a))

15


42. Consider two random array A and B, check if they are equal (★★☆)

In [120]:
A = np.random.randint(0,2,7)
B = np.random.randint(0,2,7)
print(np.array_equal(A,B))

False


43. Make an array immutable (read-only) (★★☆)

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a.flags.writeable = False
a[0] = 10

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [123]:
a = np.random.random((10, 2))
x, y = a[:, 0], a[:, 1]
radius = np.sqrt(x**2 + y**2)
angle = np.arctan2(y, x)
polar = np.column_stack((radius, angle))
print(polar)

[[0.87033277 1.4698695 ]
 [0.95906149 1.5277748 ]
 [0.78548893 1.27713309]
 [0.56839185 0.78829276]
 [0.56660348 1.10735749]
 [0.19318654 0.29996479]
 [0.80796089 1.09939078]
 [1.03733778 1.09605638]
 [0.73825062 1.33826674]
 [0.87935712 0.14758552]]


45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [125]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.78241662 0.34912161 0.74967785 0.05495339 0.07819822 0.
 0.37043805 0.11096244 0.40521602 0.65129878]


46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)

In [128]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
X, Y = np.meshgrid(x, y)
coords = np.column_stack((X.ravel(), Y.ravel()))
print(coords)

[[0.   0.  ]
 [0.25 0.  ]
 [0.5  0.  ]
 [0.75 0.  ]
 [1.   0.  ]
 [0.   0.25]
 [0.25 0.25]
 [0.5  0.25]
 [0.75 0.25]
 [1.   0.25]
 [0.   0.5 ]
 [0.25 0.5 ]
 [0.5  0.5 ]
 [0.75 0.5 ]
 [1.   0.5 ]
 [0.   0.75]
 [0.25 0.75]
 [0.5  0.75]
 [0.75 0.75]
 [1.   0.75]
 [0.   1.  ]
 [0.25 1.  ]
 [0.5  1.  ]
 [0.75 1.  ]
 [1.   1.  ]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [131]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

C = np.reciprocal(np.subtract.outer(X, Y))
print(C)

[[ 0  0  0]
 [ 0  0  0]
 [-1  0  0]]


48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [132]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f'{dtype}: min={info.min}, max={info.max}')
    
for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f'{dtype}: min={info.min}, max={info.max}')
    
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f'{dtype}: min={info.min}, max={info.max}')
    
for dtype in [np.complex64, np.complex128]:
    info = np.finfo(dtype)
    print(f'{dtype}: min={info.min}, max={info.max}')

<class 'numpy.int8'>: min=-128, max=127
<class 'numpy.int16'>: min=-32768, max=32767
<class 'numpy.int32'>: min=-2147483648, max=2147483647
<class 'numpy.int64'>: min=-9223372036854775808, max=9223372036854775807
<class 'numpy.uint8'>: min=0, max=255
<class 'numpy.uint16'>: min=0, max=65535
<class 'numpy.uint32'>: min=0, max=4294967295
<class 'numpy.uint64'>: min=0, max=18446744073709551615
<class 'numpy.float16'>: min=-65504.0, max=65504.0
<class 'numpy.float32'>: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
<class 'numpy.float64'>: min=-1.7976931348623157e+308, max=1.7976931348623157e+308
<class 'numpy.complex64'>: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
<class 'numpy.complex128'>: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


49. How to print all the values of an array? (★★☆)

In [134]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [138]:
a = np.arange(20)
x = 4.443
index = np.abs(a - x).argmin()
print(a[index])

4


51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [139]:
pos_color_dtype = np.dtype([('position', [('x', float), ('y', float)]),
                            ('color', [('r', int), ('g', int), ('b', int)])])

arr = np.array([((1.0, 2.0), (255, 0, 0)),
                ((3.0, 4.0), (0, 255, 0)),
                ((5.0, 6.0), (0, 0, 255))], dtype=pos_color_dtype)

print(arr)

[((1., 2.), (255,   0,   0)) ((3., 4.), (  0, 255,   0))
 ((5., 6.), (  0,   0, 255))]


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [140]:
a = np.random.random((100, 2))
distances = np.linalg.norm(a[:, np.newaxis, :] - a[np.newaxis, :, :], axis=-1)
print(distances)

[[0.         0.77435349 0.78384627 0.95089763 0.83095242 0.5458594
  0.34925186 0.30356523 0.9106131  0.77145557 0.40845372 0.46687661
  0.81998395 0.53375066 0.64977023 0.38006692 0.79511457 1.02822771
  0.54164176 0.7612708  0.07175903 0.12983057 0.55746995 0.19421696
  0.56603133 0.38672492 1.01740847 0.96144852 0.93229176 0.31926027
  0.75714164 0.52640078 0.55426106 0.8220872  0.48241515 0.64261632
  0.47568785 0.83204404 0.39235515 0.90115866 0.62918084 0.9170264
  0.23775533 0.27645664 0.35527108 0.54498693 0.34491469 0.44478383
  0.95912488 1.05395697 0.91567981 0.68035188 0.77884186 0.50747497
  0.57914843 0.55211569 0.97771712 0.74527682 0.10033591 0.52968468
  0.46008741 0.40845907 0.93168233 0.15335712 0.28020762 0.37158236
  1.02589332 0.31348487 0.57278087 0.4493984  0.33424981 0.72874963
  0.85365015 0.951662   0.82982    0.44244042 0.28349118 0.84803559
  0.8032684  0.41802571 0.34971413 1.04697058 0.46408436 0.20613733
  0.97087699 0.26524651 0.77365676 0.85169757 0.32

53. How to convert a float (32 bits) array into an integer (32 bits) in place? (★★☆)


In [144]:
a = (np.random.rand(10)*5).astype(np.float32)
int_a = a.view(np.int32)
print(int_a)

[1075679155 1071657071 1065453460 1061993085 1077118585 1074710197
 1082710284 1083296245 1082933272 1083865083]


54. How to read the following file? (★★☆)
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

In [ ]:
data = np.genfromtxt('file.csv', delimiter=',', filling_values=np.nan)

print(data)

55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [145]:
arr = np.array([[1, 2], [3, 4]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


56. Generate a generic 2D Gaussian-like array (★★☆)


In [146]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

57. How to randomly place p elements in a 2D array? (★★☆)

In [147]:
arr = np.zeros((5, 5))
p = 5
indices = np.random.randint(0, arr.size, p)
arr.flat[indices] = 1
print(arr)

[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


58. Subtract the mean of each row of a matrix (★★☆)

In [150]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a = A - A.mean(axis = 1).reshape(-1, 1)
print(a)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


59. How to sort an array by the nth column? (★★☆)

In [151]:
A = np.random.randint(0,10,(3,3))
print(A)
print(A[A[:,1].argsort()]) 

[[4 6 6]
 [1 9 8]
 [4 1 7]]
[[4 1 7]
 [4 6 6]
 [1 9 8]]


60. How to tell if a given 2D array has null columns? (★★☆)

In [152]:
arr = np.array([[1, 2, 3], [0, 0, 0], [4, 5, 6]])
# check for null columns
null_cols = np.any(arr == 0, axis=0)
print(null_cols)

[ True  True  True]


61. Find the nearest value from a given value in an array (★★☆)

In [154]:
def nearest_value(a, v):
    i = (np.abs(a - v).argmin())
    return a[i]
a = np.linspace(1, 10, 15)
v = 3
print(nearest_value(a, v))

2.928571428571429


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [155]:
a = np.random.random((1, 3))
b = np.random.random((3, 1))
it = np.nditer([a, b], flags=['external_loop'], op_flags=[['readonly'], ['readonly']])
sum = 0
for a, b in it:
    sum += a + b
print(sum)

[3.94815092 2.16521981 3.94470411]


63. Create an array class that has a name attribute (★★☆)

In [156]:
class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="unnamed"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', 'unnamed')
a = NamedArray(np.arange(10), "range_10")
print (a.name)

range_10


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [160]:
a = np.array([1, 1, 2, 3, 3, 3, 4, 4, 5, 5])
ind = np.array([0, 2, 3, 3, 4])
np.add.at(a, ind, 1)

print(a)

[2 1 3 5 4 3 4 4 5 5]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [161]:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 2, 0, 1])
F = np.zeros(3)

np.add.at(F, I, X)

print(F)

[5. 7. 3.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [162]:
img = np.random.randint(0, 256, size=(100, 100, 3), dtype=np.uint8)

img_2d = img.reshape((img.shape[0] * img.shape[1], 3))

unique_colors = np.unique(img_2d, axis=0)

num_unique_colors = len(unique_colors)

print("Number of unique colors:", num_unique_colors)

Number of unique colors: 9998


67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [163]:
arr = np.random.rand(2, 3, 4, 5)

sum_last_two = np.sum(arr, axis=(-2, -1))

print(sum_last_two.shape)

(2, 3)


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)

In [164]:
D = np.random.rand(10)
S = np.random.randint(0, 3, size=10)

count = np.bincount(S, minlength=np.max(S)+1)
sums = np.bincount(S, weights=D, minlength=np.max(S)+1)
means = sums / count
print(means)

[0.74612982 0.25794732 0.15725669]


69. How to get the diagonal of a dot product? (★★★)

In [165]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

dot_product = np.dot(A, B)
diagonal_elements = np.diagonal(dot_product)

print(diagonal_elements)

[19 50]


70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [167]:
x = np.array([1, 2, 3, 4, 5])
n_zeros = 3
y = np.zeros(len(x) + (len(x) - 1) * n_zeros)
y[::n_zeros + 1] = x

print(y)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [168]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. How to swap two rows of an array? (★★★)

In [3]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr[[1, 2]] = arr[[2, 1]]
print(arr)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

In [5]:
triplets = np.random.randint(0, 10, size=(10, 3))
segments = set()

for triplet in triplets:
    for i in range(3):
        j = (i + 1) % 3
        segment = tuple(sorted((triplet[i], triplet[j])))
        segments.add(segment)

print(list(segments))

[(3, 4), (3, 7), (4, 6), (0, 2), (8, 9), (1, 6), (6, 8), (0, 1), (8, 8), (1, 2), (2, 7), (7, 9), (6, 7), (4, 7), (3, 8), (0, 0), (0, 3), (1, 4), (0, 6), (2, 6), (6, 6), (7, 8)]


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [6]:
C = np.bincount([0, 1, 2, 0, 1, 2, 2, 1, 0, 0])
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 0 0 0 1 1 1 2 2 2]


75. How to compute averages using a sliding window over an array? (★★★)

In [9]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = np.arange(20)
print(moving_average(a, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [10]:
def sliding_window_array(Z, window_size):
    n_rows = len(Z) - window_size + 1
    window_view = np.lib.stride_tricks.as_strided(Z, shape=(n_rows, window_size), strides=(Z.strides[0], Z.strides[0]))
    return np.vstack(window_view)

a = np.array([1, 2, 3, 4, 5, 6, 7])
window_size = 3
print(sliding_window_array(a, window_size))

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]]


77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [11]:
a = np.random.randint(0, 2, 15)
np.logical_not(a, out = a)
a = np.random.uniform(-1.0, 1.0, 15)
np.negative(a, out = a)

array([-0.63987346,  0.32093042, -0.09677582, -0.61125782, -0.50865664,
       -0.516251  , -0.57815511,  0.95068735,  0.74331067, -0.81054104,
       -0.45353209,  0.93576535, -0.54322899,  0.74990735, -0.45534688])

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [15]:
P0 = np.array([[0, 0], [1, 1], [2, 2]])
P1 = np.array([[1, 0], [1, 3], [3, 3]])

p = np.array([1, 2])
distances = []
for i in range(len(P0)):
    x1, y1 = P0[i]
    x2, y2 = P1[i]
    x0, y0 = p
    dist = abs((y2 - y1) * x0 - (x2 - x1) * y0 + x2 * y1 - y2 * x1) / np.sqrt((y2 - y1) ** 2 + (x2 - x1) ** 2)
    distances.append(dist)

distances = np.array(distances)
print(distances)

[2.         0.         0.70710678]


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [17]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis = 1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.2663912   0.30936533  3.28002101  7.39607043 15.60040976  5.09293792
  11.36018326  4.8175657  12.01785051  6.09339907]
 [ 1.7503836   8.24251298  5.52122638  1.15420365 12.21268466 15.71316443
   0.36781838  0.98307717  3.44739044  4.10927238]
 [ 0.38684369 10.79873061  4.38669296  1.28581238 10.09283486 17.23907913
   1.72668088  1.19619735  0.89106991  6.56638812]
 [ 7.9376274  12.8029292   6.26220822  6.30489109  2.44227526  9.51927896
   3.07373843  8.49249093  1.08372579  5.28814737]
 [ 0.44044217  3.01791724  1.59218322  3.13941636 10.75762604  3.97704363
  10.87538307  0.0368973   8.70069183  4.01009334]
 [ 9.73772244 18.38677713  3.97550968 10.1184138   0.73550759 17.20582713
   4.64711419 10.5247851   6.68219378 12.22022257]
 [ 0.90616112  6.05561245  0.95836534  0.87061012  9.45470412  7.60117664
   7.0779335   1.41805319  5.65688647  0.43931076]
 [ 7.78525558 16.22707892  2.77316631  7.97930155  2.6761254  16.13934654
   3.03845521  8.54397431  4.52314516 10.224311  ]


80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

In [19]:
def extract_subpart(arr, shape, center, fill_value=0):
    """
    Extracts a subpart of an array with a fixed shape and centered on a given element.
    If the subpart goes out of bounds, it is padded with the fill value.
    
    Parameters:
    -----------
    arr : numpy.ndarray
        The input array.
    shape : tuple of int
        The shape of the subpart to extract.
    center : tuple of int
        The coordinates of the center of the subpart to extract.
    fill_value : scalar, optional
        The value to use for padding when the subpart goes out of bounds.
        Default is 0.
    
    Returns:
    --------
    subpart : numpy.ndarray
        The extracted subpart of the array.
    """
    half_shape = np.array(shape) // 2
    start = np.array(center) - half_shape
    end = start + shape
    
    pad_start = np.maximum(0, -start)
    pad_end = np.maximum(0, end - np.array(arr.shape))
    
    start = np.maximum(start, 0)
    end = np.minimum(end, np.array(arr.shape))
    
    subpart = np.ones(shape, dtype=arr.dtype) * fill_value
    subpart[pad_start[0]:shape[0]-pad_end[0], pad_start[1]:shape[1]-pad_end[1]] = arr[start[0]:end[0], start[1]:end[1]]
    
    return subpart
a = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
print(extract_subpart(a, shape, position, fill))

[[0 0 0 0 0]
 [0 3 1 5 5]
 [0 8 6 5 9]
 [0 3 3 7 4]
 [0 5 4 1 3]]


81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [21]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R = np.vstack([Z[i:i + 4] for i in range(len(Z) - 3)])
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. Compute a matrix rank (★★★)

In [24]:
a = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(a)
print(rank)

10


83. How to find the most frequent value in an array?

In [38]:
a = np.random.randint(0, 10, 20)
a = np.bincount(a).argmax()
print(a)

3


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [39]:
matrix = np.random.randint(0, 10, size=(10, 10))
block_size = 3

output_shape = (matrix.shape[0] - block_size + 1, matrix.shape[1] - block_size + 1, block_size, block_size)
strides = matrix.strides + matrix.strides
blocks = np.lib.stride_tricks.as_strided(matrix, shape=output_shape, strides=strides)

print(blocks)

[[[[0 5 9]
   [2 0 1]
   [9 5 4]]

  [[5 9 0]
   [0 1 1]
   [5 4 6]]

  [[9 0 6]
   [1 1 3]
   [4 6 9]]

  [[0 6 7]
   [1 3 8]
   [6 9 5]]

  [[6 7 2]
   [3 8 3]
   [9 5 9]]

  [[7 2 6]
   [8 3 3]
   [5 9 2]]

  [[2 6 6]
   [3 3 2]
   [9 2 5]]

  [[6 6 2]
   [3 2 5]
   [2 5 5]]]


 [[[2 0 1]
   [9 5 4]
   [6 5 7]]

  [[0 1 1]
   [5 4 6]
   [5 7 3]]

  [[1 1 3]
   [4 6 9]
   [7 3 0]]

  [[1 3 8]
   [6 9 5]
   [3 0 2]]

  [[3 8 3]
   [9 5 9]
   [0 2 3]]

  [[8 3 3]
   [5 9 2]
   [2 3 1]]

  [[3 3 2]
   [9 2 5]
   [3 1 9]]

  [[3 2 5]
   [2 5 5]
   [1 9 9]]]


 [[[9 5 4]
   [6 5 7]
   [8 8 0]]

  [[5 4 6]
   [5 7 3]
   [8 0 8]]

  [[4 6 9]
   [7 3 0]
   [0 8 6]]

  [[6 9 5]
   [3 0 2]
   [8 6 6]]

  [[9 5 9]
   [0 2 3]
   [6 6 1]]

  [[5 9 2]
   [2 3 1]
   [6 1 4]]

  [[9 2 5]
   [3 1 9]
   [1 4 3]]

  [[2 5 5]
   [1 9 9]
   [4 3 5]]]


 [[[6 5 7]
   [8 8 0]
   [5 4 9]]

  [[5 7 3]
   [8 0 8]
   [4 9 3]]

  [[7 3 0]
   [0 8 6]
   [9 3 8]]

  [[3 0 2]
   [8 6 6]
   [3 8 2]]

  [[0 2 3]
   

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)


In [40]:
class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        return obj

    def __eq__(self, other):
        return np.array_equal(self, other) or np.array_equal(self, other.T)

    def __ne__(self, other):
        return not self.__eq__(other)
Z = SymmetricArray(np.random.rand(5,5))
print(Z)

[[0.97875473 0.73253394 0.05879978 0.5468892  0.00836904]
 [0.46797794 0.98032715 0.72703733 0.77191291 0.66468762]
 [0.7332074  0.86786182 0.40023533 0.09203108 0.50524642]
 [0.80551974 0.70981255 0.15002798 0.56567664 0.63637564]
 [0.7471163  0.11272931 0.26399302 0.01601995 0.64809716]]


86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [42]:
p = 3
n = 4
matrices = np.random.rand(p, n, n)
vectors = np.random.rand(p, n, 1)
result = np.einsum('ijk,ikl->jl', matrices, vectors)
print(result)

[[2.35340542]
 [1.69275111]
 [2.72834501]
 [2.70456643]]


87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [46]:
a = np.ones((16,16))
k = 4
sum = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], k), axis=0),
                                       np.arange(0, a.shape[1], k), axis=1)
print(sum)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88. How to implement the Game of Life using numpy arrays? (★★★)

In [47]:
board = np.zeros((16, 16), dtype = int)
def next_generation(board):
    # create a new board to store the next generation
    new_board = np.zeros(board.shape, dtype=int)

    # loop over every cell in the board
    for i in range(board.shape[0]):
        for j in range(board.shape[1]):
            # count the number of live neighbors for this cell
            num_neighbors = np.sum(board[max(0, i-1):min(i+2, board.shape[0]), max(0, j-1):min(j+2, board.shape[1])]) - board[i, j]

            # apply the rules of the game to determine the state of the cell in the next generation
            if board[i, j] == 1 and (num_neighbors == 2 or num_neighbors == 3):
                new_board[i, j] = 1
            elif board[i, j] == 0 and num_neighbors == 3:
                new_board[i, j] = 1

    return new_board
for i in range(10):
    board = next_generation(board)

89. How to get the n largest values of an array (★★★)

In [48]:
a = np.arange(10000)
np.random.shuffle(a)
n = 5

print (a[np.argsort(a)[-n:]])

[9995 9996 9997 9998 9999]


90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [52]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5])
v3 = np.array([6, 7, 8])
grid = np.meshgrid(v1, v2, v3, indexing='ij')
cartesian_product = np.stack(grid, axis=-1).reshape(-1, len(grid))

print(cartesian_product)

[[1 4 6]
 [1 4 7]
 [1 4 8]
 [1 5 6]
 [1 5 7]
 [1 5 8]
 [2 4 6]
 [2 4 7]
 [2 4 8]
 [2 5 6]
 [2 5 7]
 [2 5 8]
 [3 4 6]
 [3 4 7]
 [3 4 8]
 [3 5 6]
 [3 5 7]
 [3 5 8]]


91. How to create a record array from a regular array? (★★★)

In [53]:
a = np.array([1, 2, 3])
b = np.array(['a', 'b', 'c'])
c = np.array([0.1, 0.2, 0.3])

rec = np.rec.fromarrays([a, b, c], names='field1,field2,field3')

print(rec)

[(1, 'a', 0.1) (2, 'b', 0.2) (3, 'c', 0.3)]


92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [49]:
Z = np.random.rand(int(5e5)) 
%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z, Z, Z)

40.7 ms ± 998 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
5.07 ms ± 204 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.38 ms ± 54.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [56]:
A = np.random.randint(0, 10, size=(8, 3))
B = np.random.randint(0, 10, size=(2, 2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2]


94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [61]:
A = np.array([[1, 2, 3],
              [2, 2, 3],
              [4, 5, 6],
              [7, 7, 7],
              [8, 9, 9],
              [8, 8, 8],
              [2, 2, 2],
              [3, 3, 3],
              [1, 1, 1],
              [4, 4, 4]])

unique_rows = np.unique(A, axis=1)
unequal_rows = A[np.where(np.apply_along_axis(len, 1, unique_rows) != 1)]

print(unique_rows)

[[1 2 3]
 [2 2 3]
 [4 5 6]
 [7 7 7]
 [8 9 9]
 [8 8 8]
 [2 2 2]
 [3 3 3]
 [1 1 1]
 [4 4 4]]


95. Convert a vector of ints into a matrix binary representation (★★★)

In [57]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. Given a two dimensional array, how to extract unique rows? (★★★)

In [62]:
Z = np.random.randint(0,2,(6,3))
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [51]:
A = np.random.uniform(0, 10, 20)
B = np.random.uniform(0, 10, 20)
np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[63.61936101, 59.81431098, 40.79874701, 49.20803571,  2.57843358,
         9.76098789, 39.30246413, 10.10774324, 36.22352214, 62.00158004,
        42.21678629, 32.60453863, 50.37778618, 51.74344463, 36.02107232,
        49.87066671,  2.1245596 , 46.06363646, 10.32355682, 70.34595227],
       [70.36687643, 66.15826005, 45.12589162, 54.42707555,  2.85190411,
        10.79624532, 43.47091189, 11.17977779, 40.06541509, 68.57751245,
        46.69432917, 36.06259957, 55.72089061, 57.23139178, 39.8414933 ,
        55.15998568,  2.34989193, 50.94917904, 11.41848072, 77.80689482],
       [68.60764919, 64.50425153, 43.99770884, 53.06635587,  2.78060426,
        10.5263307 , 42.38410491, 10.90027456, 39.06374821, 66.86302071,
        45.52693422, 35.16100622, 54.32782453, 55.80056198, 38.84542464,
        53.78094267,  2.29114278, 49.67540951, 11.13300972, 75.86166127],
       [41.71658763, 39.22153424, 26.75261867, 32.2667707 ,  1.69073453,
         6.40049035, 25.7714737 ,  6.62786532, 2

98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [63]:
import numpy as np
X = np.random.rand(100)
Y = np.random.rand(100)

path_length = np.cumsum(np.sqrt(np.diff(X)**2 + np.diff(Y)**2))
path_length = np.insert(path_length, 0, 0)

num_samples = 20

samples = np.linspace(0, path_length[-1], num_samples)

x_samples = np.interp(samples, path_length, X)
y_samples = np.interp(samples, path_length, Y)

print(np.column_stack((x_samples, y_samples)))

[[0.96514835 0.74672418]
 [0.71367694 0.62745003]
 [0.92622792 0.18799193]
 [0.46344197 0.39879295]
 [0.0339927  0.55184983]
 [0.29484847 0.44961857]
 [0.31713345 0.29725877]
 [0.31861167 0.16462938]
 [0.87261452 0.78310931]
 [0.2582757  0.79809257]
 [0.33140478 0.15844896]
 [0.73997261 0.87395315]
 [0.4472727  0.38487111]
 [0.11420922 0.43271062]
 [0.76768588 0.97419035]
 [0.15563874 0.64625149]
 [0.30228984 0.48528196]
 [0.85844423 0.72141965]
 [0.50640047 0.35385061]
 [0.20439814 0.80100022]]


99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [76]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [64]:
X = np.random.randn(100) 
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.360318   -0.00259304]
